# Generated by Django 5.0.6 on 2024-07-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_projects_remove_profile_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='objective',
            field=models.TextField(max_length=600),
        ),
    ]
